ppc64le: failed attempt to build with ibmnpu but missing library kills it
ERROR: modpost: "ibmnpu_lib_shutdown" [/home/aik/p/nvidia-open/kernel-open/nvidia.ko] undefined!                                            │  3 nvidia/nv-kernel.o_binary|| Binary file
ERROR: modpost: "ibmnpu_lib_register_device" [/home/aik/p/nvidia-open/kernel-open/nvidia.ko] undefined!                                     │~
ERROR: modpost: "ibmnpu_lib_stop_device_mmio" [/home/aik/p/nvidia-open/kernel-open/nvidia.ko] undefined!                                    │~
ERROR: modpost: "ibmnpu_lib_service_device" [/home/aik/p/nvidia-open/kernel-open/nvidia.ko] undefined!                                      │~
ERROR: modpost: "ibmnpu_lib_initialize_device" [/home/aik/p/nvidia-open/kernel-open/nvidia.ko] undefined!                                   │~
ERROR: modpost: "ibmnpu_lib_initialize" [/home/aik/p/nvidia-open/kernel-open/nvidia.ko] undefined!                                          │~

These used to be in nvidia/nv-kernel.o_binary

Signed-off-by: Alexey Kardashevskiy <aik@ozlabs.ru>